# profiles 값 할당 전
server:
    port: 8081
    servlet:
      context-path: /
spring:
  devtools:
    livereload:
      enabled: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  thymeleaf:
        prefix : classpath:templates/
        suffix : .html
        cache : false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/test
    username: mall
    password: mall
  redis:
    host: localhost
    port: 6379   
   
mybatis:
  config-location: classpath:mybatis/configuration.xml
  